using System.Collections.Generic;
using FrEee.Modding.Abilities;
using FrEee.Objects.Civilization;
using FrEee.Objects.Civilization.Orders;
using FrEee.Objects.GameState;
using FrEee.Objects.Space;
using FrEee.Utility;

namespace FrEee.Vehicles;

/// <summary>
/// A vehicle that can be in space on its own.
/// </summary>
public interface ISpaceVehicle
	: IVehicle, IMobileSpaceObject<ISpaceVehicle>
{
	int CargoStorage { get; }
	IDictionary<PathfinderNode<Sector>, ISet<PathfinderNode<Sector>>> DijkstraMap { get; set; }
	int EngineSupplyBurnRate { get; }
	ResourceQuantity GrossIncome { get; }
	long PopulationStorageFree { get; }
	Progress SupplyFill { get; }
	new IList<IOrder> Orders { get; }

	/// <summary>
	/// Emergency speed generated by activated emergency propulsion components. Only available for one turn.
	/// </summary>
	int EmergencySpeed { get; set; }
}