@FrEee.WebHost_HostAddress = http://localhost:5124

GET {{FrEee.WebHost_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{FrEee.WebHost_HostAddress}}/account/login
Content-Type: application/json
Accept: application/json
Accept-Language: en-US,en;q=0.5

{
    "username": "bloodninja",
    "password": "hunter2"
}