name: Release

on:
  release:
    types: [ published ]

jobs:
  announce:
    runs-on: windows-latest
    steps:
    - name: Discord release notification
      uses: SethCohen/github-releases-to-discord@v1.19.0
      with:
        # Discord's webhook url. Use GH repo secrets.
        webhook_url: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        # Decimal color value for embed.
        #color: # optional, default is 2105893
        # String username for webhook.
        username: FrEee Release Bot
        # String url to webhook avatar picture.
        #avatar_url: # optional, default is https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png            
